mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include("search.urls")),
    path('admin/', admin.site.urls),
]

mysite/search/urls.py
from django.urls import path
from search import views

app_name = "bible_search"
urlpatterns = [
    path('', views.SearchView.as_view(), name="main"),
    path('chapter/<int:pk>', views.ChapterView.as_view(), name="chapter")
]

mysite/search/models.py
from django.db import models

# Create your models here.
class Chapter(models.Model):
    chapter_name = models.CharField(max_length=50)
    book = models.CharField(max_length=20)
    preview = models.CharField(max_length=200)

    def __str__(self):
        return self.chapter_name

class Verse(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    verse_number = models.IntegerField()
    verse_text = models.TextField()

    def __str__(self):
        return str(self.chapter) + ":" + str(self.verse_number)

mysite/search/views.py
from django.views import generic
from .models import Chapter
from search import bible_search_engine
from django.db.models import Case, When
from django.core.cache import cache
import re
from django.shortcuts import redirect

# Create your views here.
class ChapterView(generic.DetailView):
    model = Chapter
    template_name = "search/chapter.html"

class SearchView(generic.ListView):
    model = Chapter
    template_name = 'search/main.html'
    context_object_name = 'results'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        if 'page' not in request.GET and 'query_text' in request.GET:
            url = f"{request.path}?query_text={request.GET['query_text']}&page=1"
            return redirect(url)
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        query = self.request.GET.get('query_text', '').strip()
        cache_key = re.sub(r'[^a-zA-Z0-9]','', query)
        results = cache.get(cache_key)

        if results is None:
            if query:
                result_ids = [raw_result["chapterid"] for raw_result in bible_search_engine.search(query)[:50]]
                results = self.model.objects.filter(id__in=result_ids).order_by(
                    Case(*[When(id=id, then=pos) for pos, id in enumerate(result_ids)])
                )
                cache.set(cache_key, results, timeout=600)
            else:
                results = self.model.objects.none()

        return results

mysite/search/templates/search/chapter.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ chapter.chapter_name }}</title>
    {% load static %}
    <link type="text/css" rel="stylesheet" href="{% static 'search/chapter_styles.css' %}">
</head>
<h1 class="header">{{ chapter.chapter_name }}</h1>
<ol>
    {% for verse in chapter.verse_set.all %}
        <li>{{ verse.verse_text }}</li>
    {% endfor %}
</ol>
</html>

mysite/search/templates/search/main.html
<!DOCTYPE html>
<html>
<head>
    <meta name="google-site-verification" content="qVmQZFUUkAeEsvDqqOrcS0oSgmb-7yODSU4X80vLXjI" />
    {% if results %}
        <title>{{ request.GET.query_text }} Page {{ page_obj.number }}</title>
    {% else %}
        <title>Bible Search Engine</title>
    {% endif %}
    {% load static %}
    <link type="text/css" rel="stylesheet" href="{% static 'search/main_styles.css' %}">
</head>
<body>
    <h1 id="introheader"><a href="/">Welcome to the Bible Search Engine</a></h1>
    <div id="searchbar">
        <form method="GET" id="searchbox">
            <input type="text" name="query_text" value="{{ request.GET.query_text }}" placeholder="Type to Search">
            <button type="submit">Search</button>
        </form>
    </div>

    {% if results %}
        <div>
            <ul id="resultslist">
                {% for chapter in results %}
                    <li id="result">
                        <a href="chapter/{{ chapter.id }}">{{ chapter.chapter_name }}</a>
                        <p class="preview">{{ chapter.preview }}</p>
                    </li>
                {% endfor %}
            </ul>
        </div>

        {% if is_paginated %}
            <div id="pagenavigator">
                {% if page_obj.has_previous %}
                    <a href="?query_text={{ request.GET.query_text }}&page=1">First</a>
                    <a href="?query_text={{ request.GET.query_text }}&page={{ page_obj.previous_page_number }}">Previous</a>
                {% else %}
                    <a href="?query_text={{ request.GET.query_text }}&page=1">First</a>
                    <a href="?query_text={{ request.GET.query_text }}&page=1">Previous</a>
                {% endif %}

                <a>Page {{ page_obj.number }} of {{ paginator.num_pages }}</a>

                {% if page_obj.has_next %}
                    <a href="?query_text={{ request.GET.query_text }}&page={{ page_obj.next_page_number }}">Next</a>
                    <a href="?query_text={{ request.GET.query_text }}&page={{ paginator.num_pages }}">Last</a>
                {% else %}
                    <a href="?query_text={{ request.GET.query_text }}&page={{ paginator.num_pages }}">Next</a>
                    <a href="?query_text={{ request.GET.query_text }}&page={{ paginator.num_pages }}">Last</a>
                {% endif %}
            </div>
        {% endif %}
    {% endif %}
</body>
</html>